### ISSUE TITLE
Rolling hourly file with all message content

### ISSUE THREAD

**Issue by aviationds** [solacese/swim-feed-handler#1]
Note: this is not an 'issue', but rather an enhancement request. If you do not have time to work on it, perhaps you could suggest how it should be done and I (or others) could contribute. 

First of all, **_thank you_** for your work on this. I was able to download this source, modify the connection parameters, and was up and running with TFMS and TBFM SWIM output in no time. I turned off the local Solace daisy chaining and only used the local file options.  

One of the first things that folks need to add when using this or the jump start kit from SCDS is to write all the message content to hourly files (rolling files, by date/time). Once the files are stored in this manner, it makes post analysis on large data volumes much easier.  Note: most of the data science related work I want to do is in python, so either pulling the data with python or getting into an hourly file format (to begin flattening this into a CSV) for ingest into a pandas dataframe is the next step. Thanks for any response to this.

**Comment by RobertOttesen** [comment]
MessageLoggingService has been created.  This service writes the messages to a log file (with optional header) and rolls over every hour.  Adjustment to rollover can done via the logback.xml logging configuration file.
