### ISSUE TITLE
Topic strings for LAT/LONG needs to be prefixed with 0 if the absolute value <10 for geofiltering to work

### ISSUE THREAD

**Issue by TKTheTechie** [solacese/swim-feed-handler#3]
For the geofiltering to work, if the absolute value lat/long is <10, then the number will need to be prefixed with 0. This is to differentiate between a lat of 10 and a lat of 1 using the wildcard filters.
1* will capture 1.000 and 10.00 for example

**Comment by RobertOttesen** [comment]
This issue is resolved in the jsonConversion branch.
